public enum EnvironmentType {
  DWELLING, OFFICE, RETAIL, SCHOOL, OPENSPACE, HOSPITAL
}

public enum Location {
  PRIMARY, SECONDARY, TERTIARY
}

public enum Demographic {
  CHILD, ADULT, SENIOR
}

public enum AgentStatus {
  SUSCEPTIBLE, INCUBATING, INFECTIOUS_MILD, INFECTIOUS_SEVERE, CONVALESCENT, HOSPITALIZED, RECOVERED, DEAD
}

public enum AgentType { 
  COVID_19, INFLUENZA, COMMON_COLD
}

public enum Day { 
  MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
}

public enum Time {
  EARLY_MORNING, MORNING_COMMUTE, LATE_MORNING, LUNCH, AFTERNOON, AFTERNOON_COMMUTE, EVENING, NIGHT
}
