public enum LandUse {
  DWELLING, OFFICE, RETAIL, SCHOOL, OPENSPACE, HOSPITAL
}

public enum Demographic {
  CHILD, ADULT, SENIOR
}

public enum Compartment {
  SUSCEPTIBLE, EXPOSED, INFECTIOUS, RECOVERED, DEAD
}

public enum Pathogen { 
  COVID_19, INFLUENZA, COMMON_COLD
}

public enum Day { 
  MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
}

public enum Time {
  EARLY_MORNING, MORNING_COMMUTE, LATE_MORNING, LUNCH, AFTERNOON, AFTERNOON_COMMUTE, EVENING, NIGHT
}
