/**
 * Results holds a summary of timestamped values generated by the model
 */
public class ResultSeries {
  
  // List of ordered Time Stamps associated with summary data
  private ArrayList<Time> timeList;
  
  // Duration of Time associated with summary data
  private HashMap<Time, Result> series;
  
  /**
   * Constructor for ResultSeries
   */
  public ResultSeries() {
    this.timeList = new ArrayList<Time>();
    this.series = new HashMap<Time, Result>();
  }
  
  /**
   * Add a time-stamped result to the series
   *
   * @param result performance summary
   */ 
  public void addResult(Result result) {
    Time t = result.getTime();
    this.addTime(t);
    this.series.put(t, result);
  }
  
  /**
   * Add time value to ordered list
   *
   * @param t time
   */
  private void addTime(Time t) {
    if(!timeList.contains(t)) {
      this.timeList.add(t);
    }
  }
  
  /**
   * Get time value as ordered list
   */
  private ArrayList<Time> getTimes() {
    return this.timeList;
  }
  
  /**
   * Get Result associated with time
   */
  private Result getResult(Time t) {
    return this.series.get(t);
  }
}
